name: 'Stale inactivity PR'
on:
  pull_request:
    types: [opened, edited]
  schedule:
    - cron: '* * * * *'
    # - cron: '0 0 * * *'

permissions:
  pull-requests: write

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'PR is stale after inactivity in 60 days unless there is new activity'
          stale-pr-label: 'stale'
          remove-stale-when-updated: 'True'
          operations-per-run: 100
          days-before-pr-stale: 1
